import { SpaceShip } from "../Types/SpaceShip";
import { MissileName } from "./MissileName";
import { SpaceShipName } from "./SpaceShipName";

const spaceships = new Map<SpaceShipName, SpaceShip>([
  [SpaceShipName.ASTEROID_MINER, {
    name: SpaceShipName.ASTEROID_MINER,
    path: "asteroid-miner/",
    fileName:"Asteroid_Miner.glb",
    textureName:"Asteroid_Miner_BaseColor.jpg",
    laserPosition: BABYLON.Vector3.Zero(),
    missilePosition: BABYLON.Vector3.Zero(),
    dronesPosition: new BABYLON.Vector3(0, 20, 0),
    jetFirePosition: new BABYLON.Vector3(0, 0.02, -0.04),
    missileName: MissileName.MISSILE01,
    scale: 200,
  }],
  [SpaceShipName.BATTLE_CRUISER, {
    name: SpaceShipName.BATTLE_CRUISER,
    path: "battle-cruiser/",
    fileName:"Battle_Cruiser.glb",
    textureName:"Battle_Cruiser_BaseColor.jpg",
    laserPosition: BABYLON.Vector3.Zero(),
    missilePosition: BABYLON.Vector3.Zero(),
    dronesPosition: new BABYLON.Vector3(0, 20, 0),
    jetFirePosition: new BABYLON.Vector3(0, 0, -0.04),
    missileName: MissileName.MISSILE01,
    scale: 200,
  }],
  [SpaceShipName.BATTLESHIP, {
    name: SpaceShipName.BATTLESHIP,
    path: "battleship/",
    fileName:"Battleship.glb",
    textureName:"Battleship_BaseColor.jpg",
    laserPosition: BABYLON.Vector3.Zero(),
    missilePosition: BABYLON.Vector3.Zero(),
    dronesPosition: new BABYLON.Vector3(0, 20, 0),
    jetFirePosition: new BABYLON.Vector3(0, 0.02, -0.09),
    missileName: MissileName.MISSILE01,
    scale: 200,
  }],
  [SpaceShipName.COLONY_SHIP, {
    name: SpaceShipName.COLONY_SHIP,
    path: "colony-ship/",
    fileName:"Colony_Ship.glb",
    textureName:"Colony_Ship_BaseColor.jpg",
    laserPosition: BABYLON.Vector3.Zero(),
    missilePosition: BABYLON.Vector3.Zero(),
    dronesPosition: new BABYLON.Vector3(0, 20, 0),
    jetFirePosition: new BABYLON.Vector3(0, 0, -0.04),
    missileName: MissileName.MISSILE01,
    scale: 200,
  }],
  [SpaceShipName.CRAWLER, {
    name: SpaceShipName.CRAWLER,
    path: "crawler/",
    fileName:"Crawler.glb",
    textureName:"Crawler_BaseColor.jpg",
    laserPosition: BABYLON.Vector3.Zero(),
    missilePosition: BABYLON.Vector3.Zero(),
    dronesPosition: new BABYLON.Vector3(0, 20, 0),
    jetFirePosition: new BABYLON.Vector3(0, 0, -0.01),
    missileName: MissileName.MISSILE01,
    scale: 200,
  }],
  [SpaceShipName.DEMOLISHER, {
    name: SpaceShipName.DEMOLISHER,
    path: "demolisher/",
    fileName:"Demolisher.glb",
    textureName:"Demolisher_BaseColor.jpg",
    laserPosition: BABYLON.Vector3.Zero(),
    missilePosition: BABYLON.Vector3.Zero(),
    dronesPosition: new BABYLON.Vector3(0, 20, 0),
    jetFirePosition: new BABYLON.Vector3(0, 0.035, -0.04),
    missileName: MissileName.MISSILE03,
    scale: 200,
  }],
  [SpaceShipName.DESTROYER, {
    name: SpaceShipName.DESTROYER,
    path: "destroyer/",
    fileName:"Destroyer.glb",
    textureName:"Destroyer_BaseColor.jpg",
    laserPosition: BABYLON.Vector3.Zero(),
    missilePosition: BABYLON.Vector3.Zero(),
    dronesPosition: new BABYLON.Vector3(0, 20, 0),
    jetFirePosition: new BABYLON.Vector3(0, 0, -0.04),
    missileName: MissileName.MISSILE07,
    scale: 200,
  }],
  [SpaceShipName.FALCON, {
    name: SpaceShipName.FALCON,
    path: "falcon/",
    fileName:"Falcon.glb",
    textureName:"Falcon_BaseColor.jpg",
    laserPosition: BABYLON.Vector3.Zero(),
    missilePosition: BABYLON.Vector3.Zero(),
    dronesPosition: new BABYLON.Vector3(0, 20, 0),
    jetFirePosition: new BABYLON.Vector3(0, 0, -0.04),
    missileName: MissileName.MISSILE01,
    scale: 200,
  }],
  [SpaceShipName.GALLEON, {
    name: SpaceShipName.GALLEON,
    path: "galleon/",
    fileName:"Galleon.glb",
    textureName:"Galleon_BaseColor.jpg",
    laserPosition: BABYLON.Vector3.Zero(),
    missilePosition: BABYLON.Vector3.Zero(),
    dronesPosition: new BABYLON.Vector3(0, 20, 0),
    jetFirePosition: new BABYLON.Vector3(0, 0, -0.04),
    missileName: MissileName.MISSILE01,
    scale: 200,
  }],
  [SpaceShipName.HEAVY_CARGO, {
    name: SpaceShipName.HEAVY_CARGO,
    path: "heavy-cargo/",
    fileName:"Heavy_Cargo.glb",
    textureName:"Heavy_Cargo_BaseColor.jpg",
    laserPosition: BABYLON.Vector3.Zero(),
    missilePosition: BABYLON.Vector3.Zero(),
    dronesPosition: new BABYLON.Vector3(0, 20, 0),
    jetFirePosition: new BABYLON.Vector3(0, 0, -0.04),
    missileName: MissileName.MISSILE01,
    scale: 200,
  }],
  [SpaceShipName.HEAVY_CRAFT, {
    name: SpaceShipName.HEAVY_CRAFT,
    path: "heavy-craft/",
    fileName:"Heavy_Craft.glb",
    textureName:"Heavy_Craft_BaseColor.jpg",
    laserPosition: BABYLON.Vector3.Zero(),
    missilePosition: BABYLON.Vector3.Zero(),
    dronesPosition: new BABYLON.Vector3(0, 20, 0),
    jetFirePosition: new BABYLON.Vector3(0, 0, -0.04),
    missileName: MissileName.MISSILE01,
    scale: 200,
  }],
  [SpaceShipName.HEAVY_FIGHTER, {
    name: SpaceShipName.HEAVY_FIGHTER,
    path: "heavy-fighter/",
    fileName:"Heavy_Fighter.glb",
    textureName:"Heavy_Fighter_BaseColor.jpg",
    laserPosition: BABYLON.Vector3.Zero(),
    missilePosition: BABYLON.Vector3.Zero(),
    dronesPosition: new BABYLON.Vector3(0, 20, 0),
    jetFirePosition: new BABYLON.Vector3(0, 0.005, -0.04),
    missileName: MissileName.MISSILE07,
    scale: 200,
  }],
  [SpaceShipName.LIGHT_CARGO, {
    name: SpaceShipName.LIGHT_CARGO,
    path: "light-cargo/",
    fileName:"Light_Cargo.glb",
    textureName:"Light_Cargo_BaseColor.jpg",
    laserPosition: BABYLON.Vector3.Zero(),
    missilePosition: BABYLON.Vector3.Zero(),
    dronesPosition: new BABYLON.Vector3(0, 20, 0),
    jetFirePosition: new BABYLON.Vector3(0, 0, -0.04),
    missileName: MissileName.MISSILE01,
    scale: 200,
  }],
  [SpaceShipName.LIGHT_CRAFT, {
    name: SpaceShipName.LIGHT_CRAFT,
    path: "light-craft/",
    fileName:"Light_Craft.glb",
    textureName:"Light_Craft_BaseColor.jpg",
    laserPosition: BABYLON.Vector3.Zero(),
    missilePosition: BABYLON.Vector3.Zero(),
    dronesPosition: new BABYLON.Vector3(0, 20, 0),
    jetFirePosition: new BABYLON.Vector3(0, 0, -0.04),
    missileName: MissileName.MISSILE01,
    scale: 200,
  }],
  [SpaceShipName.LIGHT_FIGHTER, {
    name: SpaceShipName.LIGHT_FIGHTER,
    path: "light-fighter/",
    fileName:"Light_Fighter.glb",
    textureName:"Light_Fighter_BaseColor.jpg",
    laserPosition: BABYLON.Vector3.Zero(),
    missilePosition: BABYLON.Vector3.Zero(),
    dronesPosition: new BABYLON.Vector3(0, 20, 0),
    jetFirePosition: new BABYLON.Vector3(0, 0, -0.04),
    missileName: MissileName.MISSILE01,
    scale: 200,
  }],
  [SpaceShipName.PLANET_BOMBER, {
    name: SpaceShipName.PLANET_BOMBER,
    path: "planet-bomber/",
    fileName:"Planet_Bomber.glb",
    textureName:"Planet_Bomber_BaseColor.jpg",
    laserPosition: BABYLON.Vector3.Zero(),
    missilePosition: BABYLON.Vector3.Zero(),
    dronesPosition: new BABYLON.Vector3(0, 20, 0),
    jetFirePosition: new BABYLON.Vector3(0, 0.01, -0.05),
    missileName: MissileName.MISSILE03,
    scale: 200,
  }],
  [SpaceShipName.REAPER, {
    name: SpaceShipName.REAPER,
    path: "reaper/",
    fileName:"Reaper.glb",
    textureName:"Reaper_BaseColor.jpg",
    laserPosition: BABYLON.Vector3.Zero(),
    missilePosition: BABYLON.Vector3.Zero(),
    dronesPosition: new BABYLON.Vector3(0, 20, 0),
    jetFirePosition: new BABYLON.Vector3(0, 0, -0.04),
    missileName: MissileName.MISSILE04,
    scale: 200,
  }],
  [SpaceShipName.RECYCLER, {
    name: SpaceShipName.RECYCLER,
    path: "recycler/",
    fileName:"Recycler.glb",
    textureName:"Recycler_BaseColor.jpg",
    laserPosition: BABYLON.Vector3.Zero(),
    missilePosition: BABYLON.Vector3.Zero(),
    dronesPosition: new BABYLON.Vector3(0, 20, 0),
    jetFirePosition: new BABYLON.Vector3(0, 0, -0.04),
    missileName: MissileName.MISSILE01,
    scale: 200,
  }],
  [SpaceShipName.SPACE_STATION, {
    name: SpaceShipName.SPACE_STATION,
    path: "space-station/",
    fileName:"Space_Station.glb",
    textureName:"Space_Station_BaseColor.jpg",
    laserPosition: BABYLON.Vector3.Zero(),
    missilePosition: BABYLON.Vector3.Zero(),
    dronesPosition: new BABYLON.Vector3(0, 20, 0),
    jetFirePosition: new BABYLON.Vector3(0, 0, -0.04),
    missileName: MissileName.MISSILE01,
    scale: 200,
  }],
]);

export default spaceships;